name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
  release:
    types:
      - published

jobs:
  check-lint:
    strategy:
      matrix:
        include:
          - name: code
            tox-env: check-lint
          - name: documentation
            tox-env: docs

    name: Check ${{ matrix.name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          set -xeu
          python -VV
          pip install tox
      - name: Check ${{ matrix.name }}
        run: tox -e ${{ matrix.tox-env }}

  tests:
    strategy:
      matrix:
        include:
          - name: 3.6 unit
            python-version: 3.6
            tox-env: py36-unit-tests
            coverage-flag: unit
          - name: 3.6 integration
            python-version: 3.6
            tox-env: py36-integration-tests
            coverage-flag: integration
          - name: 3.6 acceptance
            python-version: 3.6
            tox-env: py36-acceptance-tests
            coverage-flag: ""
          - python-version: 3.7
            tox-env: py37-unit-tests,py37-integration-tests,py37-acceptance-tests
            coverage-flag: ""
          - python-version: 3.8
            tox-env: py38-unit-tests,py38-integration-tests,py38-acceptance-tests
            coverage-flag: ""


    name: Test (python ${{ matrix.name || matrix.python-version }})
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        # Set health checks to wait until postgres has started
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version}}-${{ hashFiles('setup.cfg') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version}}-
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          set -xeu
          python -VV
          pip install tox coverage
      - name: Run tox targets for ${{ matrix.python-version }}
        run: tox -e ${{ matrix.tox-env }}
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: postgres
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        if: matrix.coverage-flag
        with:
          fail_ci_if_error: true
          flags: matrix.coverage-flag
